apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: assetsflow-api
  labels:
    cloud.googleapis.com/location: asia-south1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "20"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: cloud-run-runtime-sa@assetsflow-enterprise.iam.gserviceaccount.com
      containers:
      - image: asia-south1-docker.pkg.dev/assetsflow-enterprise/assetsflow-registry/assetsflow-api:latest
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: GPS_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: GPS_KEY
              key: latest
